.eqv MAX_EXPR_SZ 64
.eqv MAX_EXPR_ARRAY_SZ 256 # 4*MAX_EXPR_SZ

### TOKEN TYPES ###
.eqv TOK_END 0
.eqv TOK_START 0
.eqv TOK_NUM 1
.eqv TOK_VAR 2
.eqv TOK_ADD 3
.eqv TOK_OPS_START 3
.eqv TOK_SUB 4
.eqv TOK_MUL 5
.eqv TOK_DIV 6
.eqv TOK_ASS 7
.eqv TOK_LPAR 8
.eqv TOK_RPAR 9
.eqv TOK_NEG 10

### CHARACTERS ###
.eqv CHR_NUL 0
.eqv CHR_NL 10
.eqv CHR_LPAR 40
.eqv CHR_RPAR 41
