.eqv MAX_EXPR_SZ 64
.eqv MAX_EXPR_ARRAY_SZ 256 # 4*MAX_EXPR_SZ

### TOKEN TYPES ###
.eqv TOK_END 0
.eqv TOK_START 0
.eqv TOK_NUM 1
.eqv TOK_VAR 2
.eqv TOK_ADD 3
.eqv TOK_OPS_START 3
.eqv TOK_SUB 4
.eqv TOK_MUL 5
.eqv TOK_DIV 6
.eqv TOK_ASS 7
.eqv TOK_NEG 8
.eqv TOK_LPAR 9
.eqv TOK_RPAR 10

### OPERATOR PRECEDENCES ###
.eqv OPP_ADD 1
.eqv OPP_SUB 1
.eqv OPP_MUL 2
.eqv OPP_DIV 2
.eqv OPP_ASS 3
.eqv OPP_NEG 0

### OPERATOR ASSOCIATIVITY
.eqv OPA_LEFT 0
.eqv OPA_RIGHT 1
.eqv OPA_NEG OPA_LEFT
.eqv OPA_ADD OPA_LEFT
.eqv OPA_SUB OPA_LEFT
.eqv OPA_MUL OPA_LEFT
.eqv OPA_DIV OPA_LEFT
.eqv OPA_ASS OPA_RIGHT

### CHARACTERS ###
.eqv CHR_NUL 0
.eqv CHR_NL 10
.eqv CHR_LPAR 40
.eqv CHR_RPAR 41
.eqv CHR_ADD 43
.eqv CHR_SUB 45
.eqv CHR_MUL 42
.eqv CHR_DIV 47
.eqv CHR_ASS 61

### ERRORS ###
.eqv ERR_NONE 0
.eqv ERR_MISFORMED_NUMBER 1
.eqv ERR_MISFORMED_STATEMENT 2
