.eqv MAX_EXPR_SZ 64
.eqv TOKEN_ARRAYS_SZ 256 # 4*MAX_EXPR_SZ

### TOKEN TYPES ###
.eqv TOK_END 0
.eqv TOK_NUM 1
.eqv TOK_VAR 2
.eqv TOK_ADD 3
.eqv TOK_SUB 4
.eqv TOK_MUL 5
.eqv TOK_DIV 6
.eqv TOK_ASS 7

### CHARACTERS ###
.eqv CHR_NUL 0
.eqv CHR_NL 10
